version: "3.7"

services:
  mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: next_sandbox
      MYSQL_USER: next_sandbox
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 33060:3306
volumes:
  mysql-data:
    driver: local
