export const GET_ITEMS_START = 'QIITA/GET_ITEMS_START';
export const GET_ITEMS_SUCCEED = 'QIITA/GET_ITEMS_SUCCEED';
export const GET_ITEMS_FAIL = 'QIITA/GET_ITEMS_FAIL';

export const GET_ITEM_START = 'QIITA/GET_ITEM_START';
export const GET_ITEM_SUCCEED = 'QIITA/GET_ITEM_SUCCEED';
export const GET_ITEM_FAIL = 'QIITA/GET_ITEM_FAIL';
